"""Initial migration

Revision ID: 5b67505ccdfa
Revises: dae8f154cafd
Create Date: 2025-03-23 20:57:46.237514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b67505ccdfa'
down_revision: Union[str, None] = 'dae8f154cafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subjects', ['name'])
    op.create_unique_constraint(None, 'teachers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'subjects', type_='unique')
    # ### end Alembic commands ###
